site_name: 1IMA projekt
site_author: Tor Vidar Arnesen

nav:
  - Home: index.md
  - About: about.md
  - Servers: Servers.md
  - PC: pc.md
  - Contact Us: contactus.md
  - Offer: Offer.md
  - Log: log.md