site_name: 1IMA projekt
site_author: Tor Vidar Arnesen

theme:
  name: mkdocs
  color_mode: auto
  nav_style: primary
  user_color_mode_toggle: on

nav:
  - Home: index.md
  - About: about.md
  - Servers: Servers.md
  - PC: pc.md
  - Contact Us: contactus.md
  - Offer: Offer.md
  - Log: log.md

